version: '3'

services:
  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - mern

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - mern

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017' # Port MongoDB
    volumes:
      - mongo-data:/data/db
    networks:
      - mern

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
