# docker-compose.yml
version: '3'
services:
  frontend:
    build:
      context: ./frontend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - '3000:3000'
    networks:
      - mern_network

  backend:
    build:
      context: ./backend
    environment:
      - BASE_URL=http://localhost:3000
      - JWT_SECRET=your_jwt_secret
      - MAILGUN_API_KEY=your_mailgun_api_key
      - MAILGUN_DOMAIN=your_mailgun_domain
    ports:
      - '5000:5000'
    networks:
      - mern_network

  database:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mern_network

networks:
  mern_network:
    driver: bridge
